### ISSUE TITLE
Default theme is not applied

### ISSUE THREAD

**Issue by yujong-lee** [dooboolab/dooboo-ui#104]
Default theme is not applied correctly.

See this [Codesandbox](https://codesandbox.io/s/dooboo-ui-button-style-dohjz?from-embed) and remove `ThemeProvider`. It is not working properly.

Although writer provided theme with default prop / value, it is not applied.

**Comment by hyochan** [comment]
I think this context is a bit different but #128 can cover this part either. Let's keep up all threads in #128.
