### ISSUE TITLE
[bug] FAB gap styling 

### ISSUE THREAD

**Issue by wndudqus** [dooboolab/dooboo-ui#135]
**Describe the bug**

Need to fix margin for the gap between the buttons.
The units for the web and mobile are different.

I forgot to check the style in web env. 
My bad, I will fix the problem ASAP.

**To Reproduce**

got to : url > FAB > click FAB
https://dooboolab.github.io/dooboo-ui/

**Expected behavior**
Needs more gap between buttons

**Screenshots**
<img width="239" alt="스크린샷 2021-10-02 오후 11 35 35" src="https://user-images.githubusercontent.com/35381940/135721093-ac90c1f0-118d-4bbb-aaa9-eb2a25ac0f23.png">

**Desktop (please complete the following information):**

- OS: [macOS 11.6]
- Browser [chrome]
- Version [94.0.4606.71]

**Comment by yujong-lee** [comment]
@wndudqus 
>I will fix the problem ASAP.

Glad to hear that! Looking forward to your work on this!

**Comment by yujong-lee** [comment]
Closed via #136
