### ISSUE TITLE
Even if the app is set to dark mode in iOS, there is a problem that the dark mode theme does not apply when switching to the background.

### ISSUE THREAD

**Issue by Jay-flow** [dooboolab/dooboo-ui#164]
**Describe the bug**
Even if the app is set to dark mode in iOS, there is a problem that the dark mode theme does not apply when switching to the background.

In the past, I have made full requests on this issue. 
[Fix the dark mode release from iOS background](https://github.com/dooboolab/dooboo-ui/pull/162)

I thought I solved this problem at that time, but the frequency of occurrence decreased, but this problem still occurs.
The same problem occurs randomly.
https://github.com/expo/expo/issues/10815#issuecomment-897325894

This problem is very difficult to solve because it doesn't always happen when you return to the app from the background.

The issue appears to be a bug occurring in iOS and is also registered as an issue in the react-native repository.
https://github.com/facebook/react-native/issues/28525

It is occurring over iOS 13.
https://github.com/facebook/react-native/issues/28525#issuecomment-666244448
https://github.com/facebook/react-native/issues/28525#issuecomment-907805294

**I tried the following methods as a solution, but they were not solved.**
> ```ts
> import { Appearance, ColorSchemeName } from 'react-native';
> import { useEffect, useRef, useState } from 'react';
> 
> export default function useColorScheme(delay = 500): NonNullable<ColorSchemeName> {
>   const [colorScheme, setColorScheme] = useState(Appearance.getColorScheme());
> 
>   let timeout = useRef<NodeJS.Timeout | null>(null).current;
> 
>   useEffect(() => {
>     Appearance.addChangeListener(onColorSchemeChange);
> 
>     return () => {
>       resetCurrentTimeout();
>       Appearance.removeChangeListener(onColorSchemeChange);
>     };
>   }, []);
> 
>   function onColorSchemeChange(preferences: Appearance.AppearancePreferences) {
>     resetCurrentTimeout();
> 
>     timeout = setTimeout(() => {
>       setColorScheme(preferences.colorScheme);   // <-- the preferences.colorScheme is light.
>     }, delay);
>   }
> 
>   function resetCurrentTimeout() {
>     if (timeout) {
>       clearTimeout(timeout);
>     }
>   }
> 
>   return colorScheme as NonNullable<ColorSchemeName>;
> }
> ```

or

> ```ts
>  const initAppearanceListener = () => {
>     const listener: Appearance.AppearanceListener = ({ colorScheme } /* <-- ignore */) => {
>       setColorScheme(Appearance.getColorScheme());
>     };
>     Appearance.addChangeListener(listener);
>     return () => Appearance.removeChangeListener(listener);
>   };
> ```

---
**To Reproduce**

1. Set the iOS device to dark mode.
2. Turn on the app that applied the theme of doboo-ui.
3. Switch to the background.
4. I'm coming back to the app.
---

**Expected behavior**
The dark theme should be maintained when returning the app from the background to the foreground.

---
**Screenshots**

https://user-images.githubusercontent.com/29420674/140461244-c0041786-2636-410b-a103-5d7b73ecb1cc.mov

---

**Smartphone (please complete the following information):**

- Device: iPhone
- OS: iOS 14.8.1
- Version: 0.1.48

---
**Additional context**
N/A

**Comment by hyochan** [comment]
Looks like this is resolved~!
