### ISSUE TITLE
[Bug report]: demos are not working

### ISSUE THREAD

**Issue by wndudqus** [dooboolab/dooboo-ui#173]
**Describe the bug**
https://dooboo-ui.dooboolab.com/
On this demo page FAB, Icon, IconButton, LoadingIndicator, SwichToggle Components are not working.

with these error messages.
<img width="712" alt="스크린샷 2021-12-27 오후 11 05 38" src="https://user-images.githubusercontent.com/35381940/147479124-8a15437d-85d6-40a1-8ba7-adaf8bcea540.png">
and It 
**To Reproduce**

1. Go to 'https://dooboo-ui.dooboolab.com/'
2. Click on 'one of(FAB, Icon, IconButton, LoadingIndicator, SwichToggle)'
3. See error

- OS: [Mac 11.6]
- Browser [chrome]
- Version [96.0.4664.110]

**Comment by yujong-lee** [comment]
@hyochan @wndudqus   I guess there are 2 choices to solve this.

1. Import `React` to missing files.
2. Upgrade expo to [44](https://blog.expo.dev/expo-sdk-44-4c4b8306584a).

How do you think?

**Comment by wndudqus** [comment]
I think importing react is safer now.
I don't know much but expo 44 is newly published in 2021 dec so... let's take some time to sattle down.

**Comment by yujong-lee** [comment]
Yeah. Actually we upgraded expo to 44 in https://github.com/dooboolab/hackatalk/pull/517, but either way is fine.

**Comment by hyochan** [comment]
Looks like the storybook problem. It might not support React 17

**Comment by hyochan** [comment]
It works now~!

**Comment by yujong-lee** [comment]
@hyochan Great!
