### ISSUE TITLE
required import disappears when installed

### ISSUE THREAD

**Issue by DevYuns** [dooboolab/dooboo-ui#244]
**Describe the bug**
I added `@expo/match-media` import statement on `package/theme/ThemeProvider.tsx` in #243.
But that statement is disappeared on other project's node_modules.

**To Reproduce**

1. Install   `"dooboo-ui": "^0.2.0-rc.3"` in an expo project.
2. Check `node_modules/@dooboo-ui/theme/lib/ThemeProvider.js` file.
3. `import '@expo/match-media';` statement are not showed.

**Expected behavior**

**Screenshots**

### In dooboo-ui/packages/theme/lib/node_modules`

<img width="1203" alt="dooboo-theme" src="https://user-images.githubusercontent.com/58724686/219384389-7b5f4c08-45dc-4fb2-93b9-80ab89c78f3c.png">

### In an external project via yarn install(no `import from '@expo/match-media'` statement)
<img width="1329" alt="other-project" src="https://user-images.githubusercontent.com/58724686/219384577-120f5175-e955-41b7-a969-606de2fe904f.png">

**Additional context**
N/A

**Comment by hyochan** [comment]
@DevYuns Looks like the pkg was not built correctly. Please try `0.10.8`

**Comment by DevYuns** [comment]
@hyochan It works now!
