### ISSUE TITLE
Custom theme type overrides default theme type properties.

### ISSUE THREAD

**Issue by DevYuns** [dooboolab/dooboo-ui#245]
**Describe the bug**
Custom theme type overrides default theme type even though I just make a `bg` property.

The theme values are works but typescript complains.

<img width="742" alt="image" src="https://user-images.githubusercontent.com/58724686/219547378-078a7050-c984-471e-b800-0ada18a28566.png">

**To Reproduce**

1. Make a custom theme according to [guide](https://dooboo-ui.dooboolab.com/?path=/docs/overview-theming--page#customizing-theme) like below.

```ts
export const light = {
  bg: {
    default: '#FFFFFF',
  },
};

export type CustomAppTheme = typeof light & DoobooTheme;

export const dark = {
  bg: {
    default: '#232323',
  },
};

export const theme = {
  light,
  dark,
};
```
2. Then, Create a type declaration file like below.

```ts
import '@emotion/react';
import type {DoobooTheme} from 'dooboo-ui';
import type {CustomAppTheme} from './theme';

type AllTheme = CustomAppTheme & DoobooTheme;

declare module '@emotion/react' {
  export interface Theme extends AllTheme {
    isMobile?: boolean;
    isTablet?: boolean;
    isDesktop?: boolean;
  }
}

declare module 'dooboo-ui' {
  export interface DoobooTheme extends AllTheme {
    isMobile?: boolean;
    isTablet?: boolean;
    isDesktop?: boolean;
  }
}

```

**Expected behavior**
Properties which are not customized should be typed.

**Comment by hyochan** [comment]
@DevYuns The document wasn't clear on using custom theme. Here is how you can achieve it.

```
export type Theme = typeof light & DoobooThemeParams;
```

It is just a matter of typescript and not functionality.

Closing due to covered.
