### ISSUE TITLE
Invalid prop type color supplied to startElement In [Button]

### ISSUE THREAD

**Issue by DevYuns** [dooboolab/dooboo-ui#251]
**Describe the bug**
When I add `Image` component directly into `startElement`, An error occurred like below.
```sh
  Warning: Failed prop type: Invalid props.style key `color` supplied to `Image`.
  Bad object: {
    "color": "#FFF"
  }
```
I think that `cloneElement` in  [this line](https://github.com/dooboolab/dooboo-ui/blob/main/main/uis/Button/index.tsx#L254) makes a problem. Since `color` prop is not supported in `<Image/>`.

**To Reproduce**

Add `<Image/>` component directly into `startElement` in [Button]`

```ts
<Button
  startElement={<Image source={IC_MASK} />}
  text={getString('LOGIN')}
/>
```

**Additional context**

To fix this problem temporality, Wrap Image component with View.

```ts
<Button
  startElement={
    <View>
       <Image source={IC_MASK} />
    </View>
   }
  loading={isLoggingIn}
  text={getString('LOGIN')}
/>
```

**Comment by hyochan** [comment]
Closes #252
