### ISSUE TITLE
[FR] Ability to change loading color in [Button]

### ISSUE THREAD

**Issue by DevYuns** [dooboolab/dooboo-ui#256]
**Is your feature request related to a problem? Please describe.**

When I customized `bacgkroundColor` or `color` to dark, It's hard to see a [LoadingElement] since loading color is fixed with `text.basic`.

https://user-images.githubusercontent.com/58724686/224252349-067be954-7f2b-438e-a255-da0b8f42401d.mov

**Describe the solution you'd like**
I think providing a `loading` styles props would be great. And how about making the [LoadingElement] have the same color as the text color?

**Comment by hyochan** [comment]
Closes via 9179168a9db11d4f8e7601baf383edf3a4d82ad8

Released in `0.2.0-rc.11`. You can use `loadingColor` prop to change the color of the loading.
