### ISSUE TITLE
Remove some chained ternaries

### ISSUE THREAD

**Issue by yujong-lee** [dooboolab/dooboo-ui#45]
I like `chained ternaries` and I love how they used in this project.
But I think sometimes `chained ternaries` are not the best option. (depends on logic)

https://github.com/dooboolab/dooboo-ui/blob/8187fcb6c8813f84561e9da667bde058b7fd1de0/main/Styled/StyledComponents.tsx#L29-L46

For example, I think above code snippet might be more readable and sustainable when written like this :

```js
{
...

  background-color: ${({theme, type, outlined, disabled}) => {
    if (disabled) return undefined; 

    if (outlined) return theme.background;

    return theme[type ?? 'primary'];
  }};
}

```

Please let me know your opinion on this. 😄

**Comment by hyochan** [comment]
I definitely agree with this point of view! Please try the `PR` if you can.

**Comment by yujong-lee** [comment]
This refactoring can be done many places in `dooboo-ui`. I only did some. There's lot left.
So anyone can contribute by doing it.

**Comment by hyochan** [comment]
Yes, #46 was just awesome!

**Comment by Einere** [comment]
@hyochan @yujong-lee 
i think this issue have to be closed.. 😉

**Comment by yujong-lee** [comment]
I'm not sure whether all the codes related to this have been fixed, but most of them seem to have been modified, so I will close it for now.

Thanks.

**Comment by Einere** [comment]
@yujong-lee 
Ah, I didn't aware of that.
I just commented because related PR is merged. sorry.. 😅
