### ISSUE TITLE
[ButtonGroup] docs not rendering.

### ISSUE THREAD

**Issue by yujong-lee** [dooboolab/dooboo-ui#60]
[This](https://dooboo-ui.dooboolab.com/?path=/docs/components-buttongroup--page) is not rendering. However, [this](https://dooboolab.github.io/dooboo-ui/) works fine.

Maybe #56 is the problem?

**Comment by hyochan** [comment]
It is because there is some error in `mdx` file. We need to debug this!

**Comment by yujong-lee** [comment]
Currently resoved. See [this](https://github.com/dooboolab/dooboo-ui/pull/64#pullrequestreview-726417176) for details.
