### ISSUE TITLE
dependency packages not installed automatically

### ISSUE THREAD

**Issue by Einere** [dooboolab/dooboo-ui#74]
**Describe the bug**

When install `dooboo-ui` and use some components, error occured like below.
```
error: Error: Unable to resolve module react-native-vector-icons from /<some_path>/node_modules/dooboo-ui/Icon/index.js: react-native-vector-icons could not be found within the project or in these directories:
  node_modules/dooboo-ui/node_modules
  node_modules
```
I found missing package list
- @emotion/react
- @emotion/native
- react-native-vector-icons

**To Reproduce**

1. create example directory by run ` npx react-native init <project_name> --template react-native-template-typescript`
1. install `dooboo-ui` by running `yarn add doooboo-ui`
2. import and use some component from `dooboo-ui` like [Get Started](https://dooboo-ui.dooboolab.com/?path=/docs/overview-getting-started--page#usage)
3. run app by `react-native start` and `react-native run-android`
4. unable to resolve module error occurred

**Expected behavior**

User don't need to install dependent packages, just installed automatically.
and don't occur "unable to resolve module error"

**Screenshots**

**Smartphone (please complete the following information):**

- Device: Google Pixel 41
- OS: Android 11
- `dooboo-ui` version : 0.1.23
- npm version : 7.20.3
- yarn version : 1.22.11

**Additional context**

**Comment by hyochan** [comment]
Thanks for trying out~! It looks like we can add to [peerDependency](https://nodejs.org/es/blog/npm/peer-dependencies/) in `package.json`. Would you like to give a `PR` for this?

In addition, we need postinstallation guide for `iOS`.
https://github.com/dooboolab/dooboo-native-ts#ios-setting-guide.

**Comment by luke-hanwook** [comment]
I reproduce same process using physical device and have same issue (module resolve dependency error)

- Device: galaxy 7 (Android 8)
- OS: widnows 10
- ```dooboo-ui``` version: 0.1.25
- yarn version : 1.22.5

![image](https://user-images.githubusercontent.com/22446853/131455400-c58d469a-cd4f-4eb3-b776-bf227a9b6420.png)

**Comment by Einere** [comment]
@luke-hanwook 
I think it because this issue hasn't released at NPM.
Please wait until release!
