### ISSUE TITLE
Limitations of border calculation in [ButtonGroup]

### ISSUE THREAD

**Issue by yujong-lee** [dooboolab/dooboo-ui#78]
Currently, `ButtonGroup`'s default `flex-direction` is `row`. And border calculation is done base on it.

But, If I change it to `column`, It breaks.

![스크린샷 2021-08-22 오후 8 46 44](https://user-images.githubusercontent.com/61503739/130353986-20d15c1a-f2db-4018-b0b3-ec15e17322ea.png)
![스크린샷 2021-08-22 오후 8 46 30](https://user-images.githubusercontent.com/61503739/130353988-3ba80b04-8f74-497a-9496-55aa554bd2f4.png)

Possible Solution: Enhance border calculation logic.

**Comment by yujong-lee** [comment]
I've done several works on `ButtonGroup`, (#53, #56, #62 ) so I'm planning to work on it too.

**Comment by hyochan** [comment]
It's great for testing out. However, I am still curious if there is a use-case on [ButtonGroup] to be used as a `column`.
This [ButtonGroup] component is inspired by the [SegmentedControl](https://developer.apple.com/design/human-interface-guidelines/ios/controls/segmented-controls/) in Cupertino design system.

Do you still think we need column? Or there might be a better idea on improving it like SegmentedControl :thinking:

**Comment by yujong-lee** [comment]
Will be re-opened if needed.
