### ISSUE TITLE
Wrong link in overview documentation

### ISSUE THREAD

**Issue by luke-hanwook** [dooboolab/dooboo-ui#83]
**Describe the bug**
function component link on first line in [getting started](https://dooboo-ui.dooboolab.com/?path=/docs/overview-getting-started--page) is page not found

**To Reproduce**

1. Click on function component link (https://blog.logrocket.com/pure-functional-components)

**Expected behavior**
page is showing

**Screenshots**
none

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 92

**Smartphone (please complete the following information):**

- Device: none
- OS: none
- Browser none
- Version none

**Additional context**
Let's found this subject togeter!
if you have any impressed article for this subject, open PR or leave a comment

**Comment by hyochan** [comment]
I think we can replace this to https://reactjs.org/docs/components-and-props.html#function-and-class-components

**Comment by luke-hanwook** [comment]
fit!

**Comment by luke-hanwook** [comment]
I will fix it
