### ISSUE TITLE
Modify relative path to absolute path.

### ISSUE THREAD

**Issue by devdubby** [dooboolab/dooboo-ui#93]
**Is your feature request related to a problem? Please describe.**
I'd like to change the file path of the project to the absolute path format.

**Describe the solution you'd like**
Because it uses many files such as components, storybooks, and styles, I think it will improve code readability if I modify it to the absolute path.

**Describe alternatives you've considered**
[reactnative.dev](https://reactnative.dev/docs/typescript#using-custom-path-aliases-with-typescript)  
This official document describes how to install the babel-plugin-module-resolver to introduce an absolute path. You can also install the babel-plugin-root-import.

**Additional context**
Is there any problem installing this package or using the absolute path? I'd appreciate it if you could leave a comment.

**Comment by luke-hanwook** [comment]
I saw a similar issue #80 
it's right? check please :smile:

**Comment by devdubby** [comment]
Oh, I didn't find it. Thank you. I will close this issue.

**Comment by luke-hanwook** [comment]
@devdubby if this PR not be merged to master, i think you can also take it.
