### ISSUE TITLE
[Checkbox, SnackbarDefault] missing key prop

### ISSUE THREAD

**Issue by HeeYeonKim98** [dooboolab/dooboo-ui#94]
**Describe the bug**
`map()` should have its own `key` prop, but the `key` prop is missing or incorrectly represented.
As a result, the following warning appears.

```
Warning: Each child in a list should have a unique "key" prop.
```

**To Reproduce**

1. Install package after `dooboo-ui` clone
2. Run emulator after `npm start`
3. Click on the component. In particular, checkboxes and snackbars
4. See warning box

**Expected behavior**
No more warning boxes, and users can use and manage their data well with key prop

**Screenshots**
 <img width="100" alt="Snackbar" src="https://user-images.githubusercontent.com/48751435/131654265-e2705b94-fe07-4812-baff-5ae70f6a7ce3.png">
 <img width="100" alt="Checkbox" src="https://user-images.githubusercontent.com/48751435/131654330-6fb95dea-7ba9-40a7-8497-54dff9627db3.png">

**Smartphone (please complete the following information):**

- Device: iPhone 12 Pro Max
- OS: iOS 14.5

**Comment by devdubby** [comment]
![스크린샷 2021-09-01 오후 8 21 00](https://user-images.githubusercontent.com/35620465/131662874-8156b9d5-6974-4bbe-87c1-f1dae0054117.png)

@HeeYeonKim98 
Have you started working on this issue? The same bug occurs in the CalendarCarousel component, so it would be good to work together.

**Comment by HeeYeonKim98** [comment]
> ![스크린샷 2021-09-01 오후 8 21 00](https://user-images.githubusercontent.com/35620465/131662874-8156b9d5-6974-4bbe-87c1-f1dae0054117.png)
> 
> @HeeYeonKim98
> Have you started working on this issue? The same bug occurs in the CalendarCarousel component, so it would be good to work together.

Oh, awesome. I will work including this. Thank you.
