### ISSUE TITLE
command error when running build:storybook in macOS

### ISSUE THREAD

**Issue by Einere** [dooboolab/dooboo-ui#97]
**Describe the bug**
When run `yarn build:storybook` in macOS, `sed` command show error like below.

```sh
sed: eb-build/index.html: No such file or directory
```

**To Reproduce**
1. Clone repository
2. run `yarn build:storybook` command in console 
3. It shows error

**Expected behavior**

it not showing error, and successfully replace `/dooboo-ui` with `.` globally.

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS BigSur 11.5.2(20G95)
- zsh: zsh 5.8 (x86_64-apple-darwin20.1.0) (with oh-my-zsh)

**Additional context**

I researched it, i found it `sed -i` option is do differently by OS (GNU or macOS)
see [stackoverflow answer](https://stackoverflow.com/questions/43171648/sed-gives-sed-cant-read-no-such-file-or-directory/43453459)
so, i changed `web-build-postinstall.sh` like below, then it works
```sh
sed -i '' -e 's/\/dooboo-ui/./g' web-build/index.html
```

but, i don't know that command will run at macOS. i think it maybe run on linux based container.. 🤔
so i'm not sure this issue need to be handled. 😅

**Comment by hyochan** [comment]
Do you still face the error if you follow below? I am also using mac and haven't seen this error.

```
yarn && yarn pre && yarn build && cd docs && yarn start
```

**Comment by Einere** [comment]
@hyochan 
oh.. it need more explanation.
that error occurs when run `yarn build:storybook` in root project.
Run `yarn start` at `/docs` is very well done. 😅

**Comment by hyochan** [comment]
I think we can close the issue after we make some better doc 👍
